---
- hosts: redhat_servers
  vars:
    nginx_user: nginx
  become: true
  become_method: su
  become_user: root
  remote_user: ansible
  roles:
    - epel
    - nginx

- hosts: debian_servers
  vars:
    nginx_user: www-data
  become: true
  become_method: sudo
  become_user: root
  remote_user: ansible
  roles:
    - nginx
